# Run all unit tests
test:
	python3 -m unittest discover tests

# Run a specific test file (edit the name if needed)
test-view:
	python3 -m unittest tests.test_view_courses

test-select:
	python3 -m unittest tests.test_select_courses

test-register:
	python3 -m unittest tests.test_register_courses

test-overlap:
	python3 -m unittest tests.test_Course_overlap

test-generate:
	python3 -m unittest tests.test_generate_schedule
	
# Run the main application
main:
	python3 main.py